runtime: python38

instance_class: F1

env_variables:
  MYSQL_USER: 'root'
  MYSQL_PASSWORD: '1234'
  MYSQL_DB: 'todo'
  MYSQL_HOST: <192.168.1.203>

handlers:
  url:
    static_dir: static/scripts
  url:
    static_dir: static/styles